# Use the official Node.js image
FROM node:latest

# Set working directory in the container
WORKDIR /app

# Install Node.js dependencies
COPY package.json package-lock.json /app/
RUN npm install

# Copy the rest of the code
COPY frontend /app/
